### PR TITLE
Add Travis CI

### PR DESCRIPTION
**Pull request by jvaltin**
Enable Travis CI.

### CODE REVIEW

**Comment by douglasbakkum** [comment]
utACK

**Comment by jvaltin** [comment]
This needs to be tested on another GNU/Linux system. @stephaniestroka - would you be willing to try it on your Fedora system?

**Comment by benma** [comment]
Error when building Dockerfile.travis:

```
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/app/node_modules/node-hid/build'
  CC(target) Release/obj.target/hidapi/hidapi/linux/hid.o
../hidapi/linux/hid.c:44:21: fatal error: libudev.h: No such file or directory
 #include <libudev.h>
                     ^
compilation terminated.
hidapi.target.mk:101: recipe for target 'Release/obj.target/hidapi/hidapi/linux/hid.o' failed
make: Leaving directory '/app/node_modules/node-hid/build'
make: *** [Release/obj.target/hidapi/hidapi/linux/hid.o] Error 1
...
The command '/bin/sh -c yarn install' returned a non-zero code: 1
```

**Comment by jvaltin** [comment]
@benma I've fixed the build issue.

**Comment by stephaniestroka** [comment]
I've got the following error when running docker.x11:
```
-bash-4.4$ ./run-ElectronDemo-x11.sh
yarn run v1.9.4
warning package.json: License should be a valid SPDX license expression
$ electron .
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by benma** [comment]
@stephaniestroka just redid the build, it all works for me. (same warning as you, but running electron works).

Do you wanna check what's different for you? (maybe something about the DISPLAY). Otherwise, pls merge.

**Comment by stephaniestroka** [comment]
Oh, yeah...Fedora is preventing write access to the socket file X1. Yay, SELinux does something useful :-)

Will merge now, because I do not need to run docker anyway.

**Pull request merged**
